version: '3.7'

services:
  redis-1:
    hostname: redis-1
    image: redis:latest
    ports:
      - "6379:6379"
      - "16379:16379"
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0 --protected-mode no --cluster-announce-ip '192.168.10.110'

  redis-2:
    hostname: redis-2
    image: redis:latest
    ports:
      - "6380:6380"
      - "16380:16380"
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0 --protected-mode no --cluster-announce-ip '192.168.10.110'

  redis-3:
    hostname: redis-3
    image: redis:latest
    ports:
      - "6381:6381"
      - "16381:16381"
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0 --protected-mode no --cluster-announce-ip '192.168.10.110'

  redis-4:
    hostname: redis-4
    image: redis:latest
    ports:
      - "6382:6382"
      - "16382:16382"
    command: redis-server --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0 --protected-mode no --cluster-announce-ip '192.168.10.110'

  redis-5:
    hostname: redis-5
    image: redis:latest
    ports:
      - "6383:6383"
      - "16383:16383"
    command: redis-server --port 6383 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0 --protected-mode no --cluster-announce-ip '192.168.10.110'

  redis-6:
    hostname: redis-6
    image: redis:latest
    ports:
      - "6384:6384"
      - "16384:16384"
    command: redis-server --port 6384 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0 --protected-mode no --cluster-announce-ip '192.168.10.110'
