version: '3.7'

services:
  redis-1:
    image: redis:7.2.4-alpine3.19
#    image: redis:6.2
    ports:
      - "6379:6379"      # Port for Redis client connections
      - "16379:16379"    # Port for Redis cluster bus (communication between nodes)
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --protected-mode no
      --cluster-announce-ip '192.168.10.110'

# --appendonly yes  - The configuration in Redis enables the Append Only File (AOF) persistence mode.
# This means that every write operation performed on the Redis server is logged to a file.
# This log can then be replayed to rebuild the state of the data in Redis after a restart,
# providing a robust way to ensure data durability.
# --bind 0.0.0.0  - Bind to all interfaces (important for Docker environments)
# --protected-mode no  - Disable protected mode to allow non-local clients
# --cluster-announce-ip '192.168.10.110'  - Announce this IP to other cluster nodes

  redis-2:
    image: redis:7.2.4-alpine3.19
    ports:
      - "6380:6380"
      - "16380:16380"
    command: >
      redis-server
      --port 6380
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --protected-mode no
      --cluster-announce-ip '192.168.10.110'

  redis-3:
    image: redis:7.2.4-alpine3.19
    ports:
      - "6381:6381"
      - "16381:16381"
    command: >
      redis-server
      --port 6381
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --protected-mode no
      --cluster-announce-ip '192.168.10.110'

  redis-4:
    image: redis:7.2.4-alpine3.19
    ports:
      - "6382:6382"
      - "16382:16382"
    command: >
      redis-server
      --port 6382
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --protected-mode no
      --cluster-announce-ip '192.168.10.110'

  redis-5:
    image: redis:7.2.4-alpine3.19
    ports:
      - "6383:6383"
      - "16383:16383"
    command: >
      redis-server
      --port 6383
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --protected-mode no
      --cluster-announce-ip '192.168.10.110'

  redis-6:
    image: redis:7.2.4-alpine3.19
    ports:
      - "6384:6384"
      - "16384:16384"
    command: >
      redis-server
      --port 6384
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --protected-mode no
      --cluster-announce-ip '192.168.10.110'
