version: '3'

services:
  redis-node1:
    hostname: redis-node1
    image: redis:7.2.4-alpine3.19
    command: ["sh", "/redis-entrypoint.sh"]
    volumes:
      - ./node1/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/redis-entrypoint.sh
    ports:
      - "6378:6378"
      - "16378:16378"

  redis-node2:
    hostname: redis-node2
    image: redis:7.2.4-alpine3.19
    command: ["sh", "/redis-entrypoint.sh"]
    volumes:
      - ./node2/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/redis-entrypoint.sh
    ports:
      - "6379:6379"
      - "16379:16379"

  redis-node3:
    hostname: redis-node3
    image: redis:7.2.4-alpine3.19
    command: ["sh", "/redis-entrypoint.sh"]
    volumes:
      - ./node3/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/redis-entrypoint.sh
    ports:
      - "6380:6380"
      - "16380:16380"

  redis-node4:
    hostname: redis-node4
    image: redis:7.2.4-alpine3.19
    command: ["sh", "/redis-entrypoint.sh"]
    volumes:
      - ./node4/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/redis-entrypoint.sh
    ports:
      - "6381:6381"
      - "16381:16381"

  redis-node5:
    hostname: redis-node5
    image: redis:7.2.4-alpine3.19
    command: ["sh", "/redis-entrypoint.sh"]
    volumes:
      - ./node5/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/redis-entrypoint.sh
    ports:
      - "6382:6382"
      - "16382:16382"

  redis-node6:
    hostname: redis-node6
    image: redis:7.2.4-alpine3.19
    command: ["sh", "/redis-entrypoint.sh"]
    volumes:
      - ./node6/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/redis-entrypoint.sh
    ports:
      - "6383:6383"
      - "16383:16383"
